services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data
    # networks:
    #   - database-network

  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
    # networks:
    #   - backend-network

  # auth:
  #   build:
  #     dockerfile: Dockerfile
  #     args:
  #       - APP_NAME=auth
  #     target: development
  #   command: pnpm exec nx run auth:serve --configuration=development
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - apps/auth/.env
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/.nx
  #     - /usr/src/app/node_modules
  #   networks:
  #     - database-network
  #     - backend-network
  #   depends_on:
  #     - postgres
  #     - rabbitmq

  # users:
  #   build:
  #     dockerfile: Dockerfile
  #     args:
  #       - APP_NAME=users
  #     target: development
  #   command: pnpm exec nx run users:serve --configuration=development
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - apps/users/.env
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/.nx
  #     - /usr/src/app/node_modules
  #   networks:
  #     - database-network
  #     - backend-network
  #   depends_on:
  #     - postgres
  #     - rabbitmq

volumes:
  postgres-data: {}

networks:
  database-network:
  backend-network:
